# This is a basic workflow to help you get started with Actions
name: KH Monthly Run

# Controls when the workflow will run
on:
  schedule:
    - cron: '30 00 1 * *' # KH
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # install the python version needed

      - name: Create .env file
        run: |
          echo "REDASH_BASE_URL=${{ secrets.REDASH_BASE_URL }}" >> .env
          echo "REDASH_API_KEY=${{ secrets.REDASH_API_KEY }}" >> .env
          echo "SLACK_TOKEN=${{ secrets.SLACK_TOKEN }}" >> .env
          echo "SLACK_CHANNEL=${{ secrets.SLACK_CHANNEL }}" >> .env

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script
        run: python -m monthly.kh